### ISSUE TITLE
Display the total number of file sizes to be deleted

### ISSUE THREAD

**Issue by xyb** [Byron/dua-cli#112]
It would be nice if display the total number of file sizes to be deleted on the right side of the interactive screen.

**Comment by Byron** [comment]
I believe this is already the case. Closing for that reason, please feel free to clarify the request if it is unjustified.

<img width="1294" alt="Screen Shot 2021-11-01 at 4 55 00 PM" src="https://user-images.githubusercontent.com/63622/139647788-a6e50c00-2427-400b-ba3d-dfa17000b2cd.png">

**Comment by xyb** [comment]
@Byron Cool. I did not notice the total size at the top of the panel. However, I would probably find it easier if it was displayed in the bottom status bar, like the "Total disk usage" information.

**Comment by Byron** [comment]
Probably, tweaks are always possible and appreciated in case you would like to give it a try. PRs welcome.
As the desired information is already displayed, this remains a non-issue though.

Please note that in order to figure out design changes, discussions are probably better suited. Usually I am trying to close issues and won't, by default, try to extract value from them in the interest of time.
