### ISSUE TITLE
_dua interactive_ only looks good with dark-themed terminals

### ISSUE THREAD

**Issue by Byron-TW** [Byron/dua-cli#13]
Compare the images

![light](https://i.imgur.com/iqNqVCp.png)
![dark](https://i.imgur.com/TcBH6R6.png)

**Comment by r-darwish** [comment]
I think that the easiest solution is not to use the white color at all, but instead maybe just use bold regular or some other color. [exa](https://github.com/ogham/exa), for example, prints directories in blue.

**Comment by DarrienG** [comment]
[That's what I ended up doing](https://gitlab.com/DarrienG/terminal-typeracer/merge_requests/2#note_179259318), but I wish there were a more elegant solution.

**Comment by vks** [comment]
The problem is [this line](https://github.com/Byron/dua-cli/blob/f4028baf655e2994459e55d62435de4456fee80f/src/interactive/widgets/entries.rs#L117), which sets the background to white for light-themed terminals, which is also chosen as a background color. Setting it to any other color fixes the readability issue. To not change the look on dark-themed terminals, the color has to be set to black, which looks bad on light-themed terminals. Unfortunately, it is not possible to detect the background color of the terminal.

I suggest review any use of `Color::Reset` and consider using [`tui::style::Modifier`](https://docs.rs/tui/0.6.2/tui/style/struct.Modifier.html) for highlighting the current line.
