### ISSUE TITLE
Opening with associated program may write over TUI

### ISSUE THREAD

**Issue by Emerentius** [Byron/dua-cli#14]
When using `Ctrl + O` to open the file, the associated program may write over the TUI. I've attached a screenshot of what happens with Nautilus. VLC does a similar thing.

![garbage](https://user-images.githubusercontent.com/9992929/59562522-ff242e00-902d-11e9-9f73-d47649ccb5f2.png)

I've used this workaround: Resize terminal, scroll, resize back and scroll again, but that's bothersome. It's probably best to suppress the output completely.

**Comment by Byron-TW** [comment]
Thanks for the screenshot! This can be fixed in `open-rs`, and I linked the issue for it. I thought it would be easiest to provide something like `open::that_with(|c| c.stdout(Stdio::Null).stderr(Stdio::Null))` - the latter new API could then be used by DUA to suppress everything or... redirect it into a buffer to show in the message slot.
