### ISSUE TITLE
Home/End keys don't work in help or mark panes

### ISSUE THREAD

**Issue by IndigoLily** [Byron/dua-cli#168]
`H` and `G` scroll to top/bottom as expected.

<table>
<tr> <th colspan="2">Additional Information</th> </tr>
<tr> <th>Dua Version</th> <td>2.20.1</td> </tr>
<tr> <th>Install Method</th> <td><code>cargo install dua-cli</code</td> </tr>
<tr> <th>Terminal</th> <td><details><summary>Alacritty</summary>with no custom keybinds for home/end</details></td> </tr>
<tr> <th>Operating System</th> <td>Arch Linux</td> </tr>
</table>

**Comment by Byron** [comment]
Thanks for reporting! I think this never really worked even though the key-bindings are configured, and is probably related to the underlying library somehow.
It probably takes some time to dig in and understand what's going on in order to fix this, with a chance that it works differently in different terminals depending on how close they are to "the spec".

**Comment by gosuwachu** [comment]
I have tested this on macOS in Terminal.app and iTerm and in both it seems to work fine.

**Comment by Byron** [comment]
@IndigoLily Could you re-validate this on your platform with the latest release?

**Comment by gosuwachu** [comment]
I have tried it in [Alacritty](https://alacritty.org/) - home/end keys do work in the help pane no problem. I suspect this was fixed either in Alacritty or one of dua's dependencies. Either way, imho this issue can be closed.

**Comment by Byron** [comment]
Let's do that, as it's easy to open a new issue or reopen this one once there is new information.
