### ISSUE TITLE
termion backend no longer works

### ISSUE THREAD

**Issue by 0323pin** [Byron/dua-cli#208]
Hi,

Building 2.24.2 with no default features, features `tui-shared` and `trash-move`, results in a broken binary.

```
~> dua i
      0   B i  <1 IO Error>
Exception: dua exited with 1
```

When building with default features everything works fine but, I'd prefer using `termion` instead of `crossterm`.

Thoughts?! If only `crossterm` is supported, please update the README.md, it's currently misleading.
Thanks!

**Comment by Byron** [comment]
Thanks for making me aware!

The linked commit fixes the README and adds some more context about the motivation.

> Building 2.24.2 with no default features, features `tui-shared` and `trash-move`, results in a broken binary.

Thanks for the hint - the `tui-shared` feature is now removed. Otherwise it's not a broken binary, it's a binary without `i/interactive`, which tries to access the `i` directory as root for the traversal and fails.

I hope that clears this up.

**Comment by 0323pin** [comment]
@Byron yes, it's clear, thanks.
I think it should have been mentioned in the release notes but, at least now it's in the README.MD 😀

I only use `dua` in interactive mode, so it appeared broken but, your explanation makes sense.
