### ISSUE TITLE
Page Up and Page Down do not work

### ISSUE THREAD

**Issue by abatkin** [Byron/dua-cli#21]
Ctrl+d and Ctrl+u work, but Page Up and Page Down do not appear to work. I have tested this with [kitty](https://sw.kovidgoyal.net/kitty/) and konsole.

Running dua 2.1.7

**Comment by Byron-TW** [comment]
Thanks for letting me know. The [marker pane code](https://github.com/Byron/dua-cli/blob/22c7eb5e34372b2883276bb7fc207df891f7df8e/src/interactive/widgets/mark.rs#L97) at least tries to handle the pageup and pagedown keys, but it turns out [the code of the selector pane](https://github.com/Byron/dua-cli/blob/22c7eb5e34372b2883276bb7fc207df891f7df8e/src/interactive/app/eventloop.rs#L115) doesn't do that!
