### ISSUE TITLE
Interactive Usage Bar Granularity

### ISSUE THREAD

**Issue by LovecraftianHorror** [Byron/dua-cli#23]
I think it would be nice to have the usage bar from interactive mode support the different eighths sections instead of just full or empty. I already have a hacky version that adds this functionality.

**Comment by vks** [comment]
It probably makes sense to use https://github.com/mitsuhiko/indicatif in the long term for this and progress reporting.

**Comment by Byron-TW** [comment]
`indicatif` would also be my choice, but it would certainly be interesting to get a look at the version that @LovecraftianHorror created to get a better idea of what they mean.

Just some notes about the current implementation.

* when scanning the disk, there is a rate-limited update every few milliseconds, but due to the way it works the actual entry (the one with the percentage and bar) updates much more rarely. Numbers take time to bubble up.
* When deleting entries, it will only send an update after each entry in the list was deleted. If big folders are deleted, there is no much to see for a while. This is something that could certainly benefit a lot from enhancements.

**Comment by LovecraftianHorror** [comment]
82333ac619e95a0635c20e9bc16b364b5f520e2d and 26b9569472ffb300d7019dbed5524fdbf688c6b8 add this functionality
