### ISSUE TITLE
Interactive mode: subdirectories are not sized in Windows 10

### ISSUE THREAD

**Issue by mardukbp** [Byron/dua-cli#53]
When executing `dua i` inside a directory in Windows 10 all subdirectories are reported as having a size of 0.0 Bytes.

**Comment by Byron** [comment]
Thanks for reporting. That's an odd one, as directories are computed by looking at the sizes of all files contained within, recursively.
If files have a size, the directories should also have a size no matter which OS `dua` runs on.

Since I cannot try it on windows myself, a fix would have to be contributed.

**Comment by rivy** [comment]
I've found the problem at https://github.com/Byron/dua-cli/blob/master/src/traverse.rs#L108.

`data.name` only contains the file name, not the full path, so `data.name.size_on_disk_fast(m)...` always ends up returning a `0` file size.

I'll post a PR with a fix tomorrow, if you'd like; I need to test the change on *nix machine (my WSL instance doesn't format correctly).

**Comment by Byron** [comment]
It's interesting, as the apparently working counterpart for the non-interactive version [indeed uses the whole path](https://github.com/Byron/dua-cli/blob/82d005b9e3ed9ce8d4441c607ec160f2f0a48b1c/src/aggregate.rs#L45). This might already be the fix here as well.

Ok, I had to try it out - and it really does want to have the filename in the entry, as it will build the path dynamically via the tree - this saves memory.

Sorry for not waiting for the PR, I was just too intrigued to finally see this issue go, but I would be happy if you could give it another round of testing on windows to verify this issue is fixed for good.

Thanks so much for your investigation and all your help!

**Comment by rivy** [comment]
> It's interesting, as the apparently working counterpart for the non-interactive version [indeed uses the whole path](https://github.com/Byron/dua-cli/blob/82d005b9e3ed9ce8d4441c607ec160f2f0a48b1c/src/aggregate.rs#L45). This might already be the fix here as well.

Yep, that was the "working baseline" that I used to trace down the bug and figure out the correction.

> Ok, I had to try it out - and it really does want to have the filename in the entry, as it will build the path dynamically via the tree - this saves memory.
> 
> Sorry for not waiting for the PR, I was just too intrigued to finally see this issue go, but I would be happy if you could give it another round of testing on windows to verify this issue is fixed for good.

No worries. I was fixing it in a different manner... your fix obviously better matches your coding style. 😄 

And, it's working on my windows machine! 🚀

> Thanks so much for your investigation and all your help!

Happy to help.

BTW, I fixed the disabled tests (see PR #61).

**Comment by Byron** [comment]
Awesome! So I will be closing this issue, finally :)!

Besides, I wouldn't mind seeing an alternative solution in case you want to share your approach/fix. In any case, if you feel it might be more maintainable or easier to understand, another PR is definitely welcome 👍.
And now, back to TUI… I think the core capability of it, to me, is supporting various backends and using a buffer-diffing approach to manipulate the terminal state efficiently. Maybe one day that will become its own crate so people can build on top of it with alternative implementations - TUI's way of forcing certain ways of usage with traits is usually in my way 😅. Anyway, off-topic, rambling, done :D.

**Comment by rivy** [comment]
> Besides, I wouldn't mind seeing an alternative solution in case you want to share your approach/fix. In any case, if you feel it might be more maintainable or easier to understand, another PR is definitely welcome 👍.

Nah, it was just a draft and I was still hacking/iterating on it. No grand refactoring is lost with it deleted. 😄
Your solution is quite understandable.

> And now, back to TUI… I think the core capability of it, to me, is supporting various backends and using a buffer-diffing approach to manipulate the terminal state efficiently. Maybe one day that will become its own crate so people can build on top of it with alternative implementations - TUI's way of forcing certain ways of usage with traits is usually in my way 😅. Anyway, off-topic, rambling, done :D.

I'm somewhat new at `rust`. I look forward to seeing your progress.

Thanks for the tool and your recent work on the windows/cross-platform story!

**Comment by mardukbp** [comment]
Thank you so much for fixing this issue!
