### ISSUE TITLE
Unsure about 'quit without delay from interactive mode'

### ISSUE THREAD

**Issue by ngirard** [Byron/dua-cli#55]
I'm afraid I don't understand what the following changelog entry for the newest 2.6.1 version means:

    quit without delay from interactive mode after having looked at big directory trees
I tried to locate the related commit but didn't succeed.
Would you mind adding a few explanations ?

Thanks !

**Comment by Byron** [comment]
Thanks for letting me know. I have updated the changelog, and also linked [the corresponding commit](https://github.com/Byron/dua-cli/commit/91aade36c71e4e14167030b6ec8c3c13dcdc1b2b) which sometimes says more than a thousand words.

In short, `dua` will now always exit instantly from interactive mode - previously there may have been delays due to having to wait for deallocating a potentially massive hashmap, i.e. for millions of deallocations.

Please feel free to comment on the closed issue.

**Comment by ngirard** [comment]
Aah, I got it not, thank you very much !
Indeed, linking to the commit also allows me to learn from your code.
Cheers!
