### ISSUE TITLE
Feature request: ARM64 release

### ISSUE THREAD

**Issue by mihaigalos** [Byron/dua-cli#68]
Hi, awesome work. Can you also please release an ARM64 linux flavor?

**Comment by mihaigalos** [comment]
(yes, I can compile it from source, but a binary on _each_ release would be awesome!)

**Comment by Byron** [comment]
Thanks for the reminder, I disabled it at some point because it was failing for some reason. However, [now it is working again](https://github.com/Byron/dua-cli/releases/tag/TEST-0.0.1) and I have enabled it permanently.

The next regular release will have an arm version, and for completeness I have added the current arm build artifact to the most recent version.

_Note_ that I am not quite sure if it works on any linux since it's not a MUSL build, judging by the filename.
