### ISSUE TITLE
Request: skip & continue when directories/files do not have permission

### ISSUE THREAD

**Issue by mburr-precor** [Byron/dua-cli#75]
When `dua` encounters a directory that it doesn't have permission to enter, the program prints an error essage and terminates:

```
$ ~/.cargo/bin/dua -f binary aggregate
Error: Permission denied (os error 13)
$ echo $?
1
```

It would be nice if it prints a more specific error message and continues, similar to `du`:

```
$ du -chs
du: cannot read directory './.config/gsmartcontrol': Permission denied
du: cannot read directory './.cache/dconf': Permission denied
du: cannot access './.cache/doc': Permission denied
du: cannot read directory './.dbus': Permission denied
du: cannot access './.gvfs': Permission denied
873G	.
873G	total
$ echo $?
1
```

My personal preference would be for this to be the default, but if it has to be enabled with an option so be it.

(`du` apparently doesn't have a way to turn off this behavior - which is fine by me).

**Comment by Byron** [comment]
Thanks for posting!

Could you verify that this behaviour only occours on the top-level? Thus, the issue above would not occour like this: `dua -f .` or `dua -f` - it should just report that there were IO errors while descending into the given directory.

Regarding the termination behaviour, I am not quite sure what happens if IO errors are encountered during traversal, my feeling is that this doesn’t affect the exit code yet. If that should be the case, it should enable the new behaviour rather than change it to prevent breakage.

**Comment by mburr-precor** [comment]
Thanks for the very quick response.

Strangely, I am unable to reproduce the behavior I ran into just yesterday even though the permissions haven't changed  (`du` still complains about the same directories).

In case you care (I don't), `dua` doesn't give an error message about the directories it shouldn't be able to enter - it just lists a 0 size for them).
