### ISSUE TITLE
Support integration with `xplr` by allowing to print paths selected for deletion

### ISSUE THREAD

**Issue by sayanarijit** [Byron/dua-cli#87]
Hi, Nice tool. I have added an [integration hack](https://github.com/sayanarijit/xplr/wiki/Hacks#disk-usage-dua-cli) with [xplr](https://github.com/sayanarijit/xplr).
However, for better integration experience, is there a way to print the selected paths? This would allow migration of the `dua-cli` selected paths to `xplr` selection.

**Comment by Byron** [comment]
Nice indeed, thanks!

Do you mean it would be nice to print paths selected for deletion upon quitting `dua`?

**Comment by sayanarijit** [comment]
Yes. Instead of deleting, it can return the paths via stdout, and then other tools can decide what to do with them.

**Comment by sayanarijit** [comment]
Maybe a command line option, something like `-p PATH` (for pipe) can be implemented. `-p /tmp/list.txt` will pipe the paths to `/tmp/list.txt`, while `-p -` will print them to stdout.

**Comment by Byron** [comment]
This should be resolved with `dua v2.13`, where `dua i` unconditionally prints remaining marked items. This _should_ be fine as the default workflow usually is to mark and delete, leaving no items in the pane. If somebody leaves them it's either because the wanted to, or because they quit by mistake. In the latter case it's probably desirable to have the paths 'memorized' in the terminal in case they want to try again.

Only for the users who quit intentionally (maybe because they changed their mind) will the new behaviour be surprising as they now see selected paths that they never care about. Lastly, in case deletion fails due to permission errors for instance, paths will be printed as well as they would remain in the pane. For these users it might also be interesting to see them as they can try again by hand with `sudo`.

This is the reasoning for printing remaining paths by default, currently without a way to turn that off.

**Comment by sayanarijit** [comment]
Thanks a lot. Really well thought out and creative solution 👍

**Comment by sayanarijit** [comment]
Hi, I tried integrating, but there's some issue.

```
➜  ~ dua i | xargs -l 'echo SelectPath: "{}"'
Error: Interactive mode requires a connected terminal
xargs: echo SelectPath: "{}": No such file or directory

➜  ~ paths=$(dua i)
Error: Interactive mode requires a connected terminal

➜  ~ dua i > x
Error: Interactive mode requires a connected terminal
```

**Comment by Byron** [comment]
A great point, sorry for the oversight.

In version 2.13.1 it's implemented so that the TUI wants to write to stderr, allowing the redirections of stdout to catch the selected files.

I hope this works now :).

**Comment by sayanarijit** [comment]
Works now. Thanks.

```
➜  ~ x=$(dua i)
➜  ~ echo $x
.android
.cargo
.pyenv
Documents
Unity
snap
```
