### ISSUE TITLE
Comparison to dust?

### ISSUE THREAD

**Issue by austinbutler** [Byron/dua-cli#90]
When searching for NCDU alternatives `dust` and `dua` come up, and both projects are written in Rust, but neither project mentions the other.

**Comment by austinbutler** [comment]
Created a similar issue with `dust`: https://github.com/bootandy/dust/issues/145

**Comment by Byron** [comment]
I am not using `dust` and hence wouldn't know what the major differences are.
Maybe starting to mention similar tools would be helpful to people landing on either one of these projects.

**Comment by austinbutler** [comment]
FWIW having tried both briefly `dust` doesn't seem like a very suitable `ncdu` replacement since I don't think it has an interactive mode.

**Comment by Byron** [comment]
It seems the motivation for this issue is mainly the comparison to NCDU and it will help me to close this issue.

My reasoning here is that NCDU users will know what they get from the tool and are able to check the video provided on the landing page to get an idea of what `dua` is for. Then they will probably know if it can or can't replace their usage of `ncdu`, or is rather a specialized utility to use on top of NCDU.

Thanks for your understanding.
